export const environment = {
  production: false,
  apiBaseUrl: 'http://localhost:3000/api/v1',
  iamEndpointPath: '/users',
  nutritionLogEndpointPath: '/nutrition-log',
  foodSearchEndpointPath: '/foods',
  bodyMetricsEndpointPath: '/body-metrics',
  analyticsEndpointPath: '/analytics',
  recommendationsEndpointPath: '/recommendations',
  pantryEndpointPath: '/pantry',
  recipesEndpointPath: '/recipes',
  ingredientCatalogEndpointPath: '/ingredient-catalog',
  subscriptionsEndpointPath: '/subscriptions',
  billingHistoryEndpointPath: '/billing-history',
  behavioralProgressEndpointPath: '/behavioral-progress',
  dailyBalanceEndpointPath: '/daily-balance',
};
